---

- name: deploying artifacts
  hosts: webservers
  become: yes
  become_user: root

  tasks:
  - name: copy file
    copy:
      src: /opt/jenkins/workspace/java-pipeline/target/springboot-bootcamp-0.0.1-SNAPSHOT.jar
      dest: /home/ubuntu
                                                  
  - name: update apt package manager repo cache
    apt:
      update_cache: yes

  - name: install java using ansible
    apt:
      name: openjdk-11-jdk
      state: present


  - name: running artifacts
    shell: nohup java -jar /home/ubuntu/springboot-bootcamp-0.0.1-SNAPSHOT.jar &

